### ISSUE TITLE
[Feature Request] 是否有可能对windows terminal实现浏览器类似的中键关闭行为

### ISSUE THREAD

**Issue by TTTPOB** [chaohershi/cclose#10]
目前windows terminal的标签页区域也会被识别为标题栏
(已经购买pro版

**Comment by chaohershi** [comment]
感谢支持！这确实是个槽点，而且不只是Windows Terminal，之前Edge浏览器的标签也是绘制在标题栏里，一样的情况，后来修复了。所以我建议去那边提个issue：https://github.com/microsoft/terminal/issues

目前你可以在Windows Terminal的配置文件里这样设置：
```json
"alwaysShowTabs": true,
"showTabsInTitlebar": false,
```
颜值会降，但标签不再绘制在标题栏里了。

![image](https://user-images.githubusercontent.com/22566267/104676812-25042f80-56b6-11eb-8cbf-acdfd9a16071.png)

参考链接：https://docs.microsoft.com/en-us/windows/terminal/customize-settings/global-settings#always-show-tabs

**Comment by chaohershi** [comment]
我去提了个[issue](https://github.com/microsoft/terminal/issues/8795)，应该等微软修复就行了。

**Comment by TTTPOB** [comment]
（啊谢谢，昨天忘记去提了
