### ISSUE TITLE
置顶窗口添加标记提示

### ISSUE THREAD

**Issue by littlegolden** [chaohershi/cclose#11]
购买了 Pro 版本，体验都挺好的，就是希望能在置顶窗口的标题栏上添加一个类似大头针固定针的标记，类似 Deskpins 软件

**Comment by chaohershi** [comment]
这个要实现要重构了，而且 Deskpins 那样的需要持续追踪窗口占用资源我不是很喜欢。不过提议很有道理，我会考虑一些有没有其他方式实现。感谢反馈！

**Comment by chaohershi** [comment]
这个要实现要重构了，而且 Deskpins 那样的需要持续追踪窗口占用资源我不是很喜欢。不过提议很有道理，我会考虑一下有没有其他方式实现。感谢反馈！

**Comment by Littlegolden** [comment]
这几天用习惯了，觉得没有标记挺简洁清爽的hhhhh
