### ISSUE TITLE
Not working with Sticky Note in Windows 10

### ISSUE THREAD

**Issue by ngtrian** [chaohershi/cclose#12]
Not working with Sticky Note in Windows 10

**Comment by chaohershi** [comment]
There are three hidden window buttons on the Sticky Notes, so you will need to click a bit to the left. Please check the attached picture for what I mean.

![Sticky Notes Not Working](https://user-images.githubusercontent.com/22566267/128460550-89f7387e-a5de-48b7-8975-abd7e651c358.png)

**Comment by ngtrian** [comment]
I followed the instructions correctly, sticky note was On top, but when I opened another window, then reopened the sticky note window, On top was disabled.

**Comment by chaohershi** [comment]
Thanks for the detailed feedback, especially the screen recording! I can't reproduce the problem on my computer (Windows 10, version 21H1). Both Sticky Notes and Calculator stay on top just fine. Mind sharing your Windows specifications? You can find them under Settings -> System -> About.

What I can confirm is this behavior occurs on some software that have their own always-on-top logic. For example, DeepL and OneNote. So basically CClose makes them always on top, and then those software later make themselves not. I will add a forceful mode in the future when I have some time.

**Comment by ngtrian** [comment]
I using Windows 10, version 21H1, OS build 19043.1151
Hope this information is useful to you.
