### ISSUE TITLE
 Pin function not working with Excel on Windows 10

### ISSUE THREAD

**Issue by HaoLi1101** [chaohershi/cclose#13]
I purchased the Pro version. I am experiencing an issue with the pin function on Excel as shown attached:
![CClose Excel Issue](https://user-images.githubusercontent.com/32119693/130975360-22b4aca8-5066-4739-b2d9-4f818c2cddab.gif)

I am not able to close the not-pinned excel window when the Excel sheet on top is pinned.

**Comment by chaohershi** [comment]
Excel is a bit unique. You need to click on the Window body/cells of the "frozen" Excel window to activate it first before you can close it.
