### ISSUE TITLE
一些窗口在使用右键最小化后再点击任务栏图标复原显示出错

### ISSUE THREAD

**Issue by ClewenWei** [chaohershi/cclose#15]
像是这样的窗口，即左上方有一个返回按钮：
![图片](https://user-images.githubusercontent.com/57256934/135092815-6da75863-b467-40d0-b426-413474a75df9.png)

还有类似蓝牙传输的窗口：
![图片](https://user-images.githubusercontent.com/57256934/135093131-16086999-f7ba-4c25-a6c8-dc9187394b8b.png)

在使用右键最小化后，再点击任务栏中的图标复原，会只显示一个小窗口，无法复原和正常操作：
![图片](https://user-images.githubusercontent.com/57256934/135093398-b946364a-ef01-4738-ab67-a7aa2e37dac8.png)

**Comment by chaohershi** [comment]
感谢反馈，确实有这个问题。没有最大化最小化按钮的窗口原本是不应该被最小化的，使用外部程序比如 CClose 强行最小化就会导致设计外的情况。我会考虑一下要不要对这样的窗口禁用最小化操作。
