### ISSUE TITLE
Does CClose prevent minimizing when going to desktop?

### ISSUE THREAD

**Issue by SoMeGoD** [chaohershi/cclose#16]
Hi! Does the feature "window always on top" maintain the pinned window on top even with the use of "WIN+D" shortcut? I need the pinned window to REALLY stay on top, even when switching to desktop view. Does CClose offer this feature?

**Comment by chaohershi** [comment]
I actually got the same feature request previously. I implemented it and made it available in CClose Pro.
"Normal" always-on-top can be minimized by `WIN + D`, but if you press `Ctrl` then toggle always-on-top, the window will be "super pinned" and immune to `WIN + D`.

Just note after you "super pinned" a window
- minimize button will disappear or won't work (can still use CClose feature to minimize the window by right click on the title bar)
- maximize button will disappear or won't work and double click on the title bar won't work
- you can't click on the taskbar button to minimize a window (but you can recover it from minimized state)
- the window may flash once to redraw the GUI

The window will go back to normal if you `Ctrl` and toggle always-on-top again.

**Comment by SoMeGoD** [comment]
I just bought the PRO version and I really appreciate this app so much. It's clean, it's simple. The persistent "always on top" is EXACTLY what I needed, and the other features I didn't really think about it became very useful. Thanks for creating it. I've left a review on the Windows Store, hope it helps out.

**Idea/Suggestion:** Is it possible to have the option to apply the "Always On Top" via Context Menu while Right-Clicking on the Title bar, or with a Keyboard Shortcut? It would be very helpful to be able to apply "Always on Top" with more ease and in a more quick manner (I use it A LOT when sharing my screen at work).

Other ideas: 

- Have some kind of visual representation that the window is pinned and fixed. DeskPin has a cool pin icon indicator that appears on the window that is pinned (the icon itself is VERY ugly, but the idea and usability is cool)
- Option to release all pinned windows at once (with a shortcut or from the menu)

**Comment by chaohershi** [comment]
Thank you for your kind review and ideas. Thanks for leaving a message in the first place.

Regarding your ideas,
- Keyboard shortcut: Yes, it is in the development roadmap.
- Visual cue: DeskPin's approach requires it to keep track of windows' state and position continuously. I want to keep my app simple and that's something I don't want to do. But I admit if multiple windows are pinned, visual cues could be helpful. I'll see if any simple and elegant solution exists.
- Release all pinned windows: I probably won't implement this. One approach is to keep track of all the windows that have been pined, which I don't want to do. Another approach is to loop through all windows and unpin them all. Such an approach's problem is that it could end up unpin other windows not pinned by CClose (other windows may have their own always-on-top logic, e.g. some video players).
