### ISSUE TITLE
cclose pro和普通版均无法右键任务栏按钮直接将光标跳到关闭选项上

### ISSUE THREAD

**Issue by littleboyzt** [chaohershi/cclose#17]
系统win10，版本17763.437

**Comment by chaohershi** [comment]
右键之后移动了鼠标，或者跳转菜单弹出时间超过 2 秒，为了避免对鼠标使用造成打扰，就不会触发跳动。

如果不是以上情况的话，可以请您提供一个截图吗？打开 CClose Pro -> 设置 -> 高级选项 -> 勾选「跟随鼠标」，然后右键任务栏按钮，将鼠标移至跳转菜单上，提供一下此时的窗口信息截图，截图可以用截图软件或者按 `PrtScn` 键，打开画板然后 `Ctrl + v`。

示例：
 
![sp20220124_001737_844](https://user-images.githubusercontent.com/22566267/150726129-81a8b3b2-9790-4b2f-a9ed-4f74a0be01b4.png)

**Comment by littleboyzt** [comment]
![20220124150020](https://user-images.githubusercontent.com/8893774/150736388-ccfc609a-3d4b-43b5-b726-5a2552cace2d.png)

**Comment by littleboyzt** [comment]
![Uploading Snipaste_2022-01-24_15-05-57.jpg…]()

**Comment by littleboyzt** [comment]
![Snipaste_2022-01-24_15-05-57](https://user-images.githubusercontent.com/8893774/150737076-139133e8-aa35-4337-969c-ba9a138acaaf.jpg)

**Comment by chaohershi** [comment]
我是基于窗口是否属于 `Windows.UI.Core.CoreWindow` 这个类，来判断窗口是否是跳转菜单的。我查了一下 `SIBJumpView`，没有找到相关信息，请问您是用了第三方桌面主题或者什么美化插件吗？

**Comment by littleboyzt** [comment]
额，没用什么三方主题和美化插件，就是用wallpaper engine搞了个动态的桌面，这个会有影响吗

**Comment by chaohershi** [comment]
应该不会的，不过还是关了试试看？

**Comment by littleboyzt** [comment]
还是一样无效，我开了鼠标跟随看了下，右键任务栏图标移到弹出菜单后还是这个SIBJumpView

**Comment by chaohershi** [comment]
好，有空我找个旧的 Windows 装一下看看能不能重现

**Comment by littleboyzt** [comment]
请问下作者，后面有重现过这个吗

**Comment by chaohershi** [comment]
你好，我最近在虚拟机安装了 Windows 10 Version 1809 (17763.437) 测试过了，没有能够重现这个问题。最初开发软件的时候，我用 Windows 版本更古早，之后一路升级都没有问题。看起来这是特定系统的问题，我也没有很好的解决办法，要不试试升级看看。
