### ISSUE TITLE
How do I compile this?

### ISSUE THREAD

**Issue by rp1231** [chaohershi/cclose#18]
I have made some shortcut changes according to my needs.
Just wanted to ask how to compile this.
Thanks

**Comment by chaohershi** [comment]
The easiest way is to install [AutoHotKey](https://www.autohotkey.com/), then from the start menu choose `Convert .ahk to .exe`. For the source select `CClose.ahk`, and for the destination, specify where you want the compiled file to be. It should be pretty straightforward.

![Snipaste_2022-08-13_12-20-07](https://user-images.githubusercontent.com/22566267/184502422-2a180242-7894-48ae-bb99-0ec53cc282d0.png)

**Comment by chaohershi** [comment]
Ah, I see. Just to add a bit of detail: `Advanced Settings.ahk` is a component of the main script `CClose.ahk`. It will be included in the main script during runtime. So they should be placed in the same folder, whether you want to compile the main script or not.
