### ISSUE TITLE
管理员权限必须性

### ISSUE THREAD

**Issue by srozanski60** [chaohershi/cclose#19]
非常喜欢cclose这个软件 个人已经使用多年。想在公司电脑使用cclose 但是没有管理员权限无法安装。请问有什么解决方法吗？谢谢。

**Comment by chaohershi** [comment]
你好，感谢使用。可以在[这里](https://github.com/chaohershi/cclose/releases/latest)下载安装包。在个人电脑安装好之后，把主程序`CClose.exe`拷贝到其他电脑上使用。程序可以不以管理员权限运行，只是会无法操作高权限窗口，比如任务管理器。另外没有管理员权限的话，想要设置程序开机启动需要手动把程序或者程序快捷方式放入启动文件夹。

**Comment by srozanski60** [comment]
明白了。谢谢您的回复，我试一下看看。Sent from my iPhoneOn Jan 26, 2023, at 14:59, Chaohe Shi ***@***.***> wrote:﻿
你好，感谢使用。可以在这里下载安装包。在个人电脑安装好之后，把主程序CClose.exe拷贝到其他电脑上使用。程序可以不以管理员权限运行，只是会无法操作高权限窗口，比如任务管理器。另外没有管理员权限的话，想要设置程序开机启动需要手动把程序或者程序快捷方式放入启动文件夹。

**Comment by srozanski60** [comment]
可以正常使用了。谢谢
