### ISSUE TITLE
Win 11系统新版资源管理器，标题栏无法被识别

### ISSUE THREAD

**Issue by chaohershi** [chaohershi/cclose#20]
程序已经以管理员身份运行

**Comment by Gahotx** [comment]
请问这个有更新的打算吗？

**Comment by chaohershi** [comment]
> 请问这个有更新的打算吗？

会更新的

**Comment by chaohershi** [comment]
[CClose Pro](https://www.microsoft.com/store/apps/9nzs8jpfz8hg) 2.4.0.0 增加了对 Windows 11 资源管理器标题栏的适配。
