### ISSUE TITLE
win11资源管理器无法置顶。装载系统盘里

### ISSUE THREAD

**Issue by SamWang8888** [chaohershi/cclose#23]
如题

**Comment by wdsgscc** [comment]
试试以管理员身份运行

**Comment by SamWang8888** [comment]
手动用管理员身份运行。还是不能置顶资源管理器

**Comment by lvxinlon** [comment]
＋1

**Comment by chaohershi** [comment]
[CClose Pro](https://www.microsoft.com/store/apps/9nzs8jpfz8hg) 2.4.0.0 增加了对 Windows 11 资源管理器标题栏的适配。
