### ISSUE TITLE
软件和游戏APEX冲突

### ISSUE THREAD

**Issue by gamersky998** [chaohershi/cclose#24]
APEX有小蓝熊检测程序，可能禁用hotkey类型的软件有关，每当开启这个软件的时候，游戏就显示这个错误，关闭了则没事
![image](https://github.com/user-attachments/assets/743e8054-73bb-4889-88b9-08aa9766bbfe)

**Comment by chaohershi** [comment]
CClose是脚本程序。部分游戏会检测是否存在脚本程序进程来防止外挂，不过无法具体区分脚本是正常程序还是外挂，只能一刀切，没有办法呢。
