### ISSUE TITLE
两个小问题，大功能用的很爽，有时间修复解答下，谢谢，😇

### ISSUE THREAD

**Issue by aizhouyi** [chaohershi/cclose#4]
1. 双击esc的小问题，双击esc的快速关闭非常炫酷好用，但是可否加入设置黑名单程序，有的程序载入贼慢，双击快了多点了esc，直接关掉，心态爆炸，比如二十多个选项卡的chrome一下关掉，即使ctrl+shift+t恢复，还是慢，希望能加入黑名单功能。
2. 某些视频播放器平常的右键功能被屏蔽了，在窗口的右键变成了最小化功能，我的实例是qq影音，
![Snipaste_2020-06-10_18-29-42](https://user-images.githubusercontent.com/57656655/84257744-6a70e500-ab48-11ea-83e5-ab8c31ede183.png)
这应该是个bug，望修复。

**Comment by chaohershi** [comment]
感谢反馈！

> 双击esc的快速关闭非常炫酷好用，但是可否加入设置黑名单程序

有这个计划，但是要等一会。8月份之后有空了我会做一下。

> QQ影音右键功能被屏蔽了

这个是QQ影音的GUI没写好😂。虽然看起来不是，但属性上整个窗口实际上是个巨大的标题栏。[CClose 1.3.13.0-beta](https://github.com/chaohershi/cclose/releases/tag/v1.3.13.0-beta)有处理这个问题。设置完重启CClose生效。有空了也会把这个设置写到主程序里，并且简化一下流程，出一个正式版。

**Comment by aizhouyi** [comment]
好的，期待黑名单功能加入。我去看下v1.3.13.0-beta版的，谢谢
