### ISSUE TITLE
网易云音乐标题栏相关功能无法预期运作

### ISSUE THREAD

**Issue by iamapig120** [chaohershi/cclose#5]

**Comment by chaohershi** [comment]
[CClose 1.3.13.0-beta](https://github.com/chaohershi/cclose/releases/tag/v1.3.13.0-beta)有处理这个问题。目前设置完需要重启CClose生效。有空了会更新一个正式版。

**Comment by iamapig120** [comment]
> [CClose 1.3.13.0-beta](https://github.com/chaohershi/cclose/releases/tag/v1.3.13.0-beta)有处理这个问题。目前设置完需要重启CClose生效。有空了会更新一个正式版。

感谢，已使用beta版本临时解决了相关问题
