### ISSUE TITLE
Windows terminal 在非标题栏右键也会最小化窗口

### ISSUE THREAD

**Issue by Tsezz** [chaohershi/cclose#8]
[Windows terminal](https://github.com/microsoft/terminal)

**Comment by chaohershi** [comment]
Pro版本有处理这个问题，你可以免费版中试用例外列表功能（托盘区图标右键，设置 -> 高级设置 -> 标题栏例外列表）。

![GIF 11-8-2020 2-21-03 AM](https://user-images.githubusercontent.com/22566267/98459516-8ca77700-2169-11eb-8bdc-f8dbb26f140b.gif)
