### ISSUE TITLE
False Positive McAfee and others?

### ISSUE THREAD

**Issue by Z0pyrus** [chaohershi/cclose#9]
https://www.virustotal.com/gui/file/b5f17baf06852db019a71744311a24becc5a48c6db72a25dc7fa5df408f007e1/detection

VirusTotal says that they found maleware

**Comment by chaohershi** [comment]
Yes, those few are false positive detections. If you have safety concerns, you may
- install [AutoHotkey](https://www.autohotkey.com/), and run/compile the source code (those with .ahk filename extension) on your own
- purchase CClose Pro from the Microsoft Store [here](https://www.microsoft.com/store/apps/9nzs8jpfz8hg)
